version: '3.8'

services:
  # Servizio per l'API (il nostro backend)
  api:
    # Dice a Compose di costruire l'immagine usando il Dockerfile
    # che si trova nella sottocartella ./simple_api
    build:
      context: ./simple_api
    container_name: student-api
    networks:
      - student-net

  # Servizio per il sito web (il nostro frontend)
  website:
    image: php:apache
    container_name: student-website
    ports:
      - "80:80"
    volumes:
      # Monta il nostro codice del sito web
      - ./website:/var/www/html
    environment:
      # Credenziali per l'autenticazione all'API
      - USERNAME=toto
      - PASSWORD=python
    # Assicura che l'API parta prima del sito web
    depends_on:
      - api
    networks:
      - student-net

# Definiamo la rete condivisa
networks:
  student-net:
    driver: bridge
